### ISSUE TITLE
Allow use of IO20 on newer ESP32 variants

### ISSUE THREAD

**Issue by bassefrom** [JetBrains/intellij-micropython#183]
IO20 wasn't available on earlier packages so it was considered invalid. Support was added in IDF recently:
https://github.com/espressif/esp-idf/commit/6deaefde69c3f068d39b76d628b05b21fd142b79

I'm using a ESP32-PICO-V3-02 and trying to set IO20 as output and receive this error: ValueError: invalid pin

**Comment by elmot** [comment]
That is not intellij-micropython issue, that is micropython itself issue.
Please retry with the newest micropython version, and if the issue persist, report to https://github.com/micropython/micropython/issues
