### ISSUE TITLE
failed to load plugin descriptor ...

### ISSUE THREAD

**Issue by perlchamp** [JetBrains/intellij-micropython#191]
i wanted to include this plugin in pycharm 2021.3. I saved the zip to my hard drive using the download.zip option button right here.

about :
File > Settings > PlugIns > install plugin from disk > intellij-micropython-master.zip

=> ERROR: failed to load plugin descriptor from file intellij-micropython-master.zip

what went wrong ?

keep corona away !
regards !

so long
pc

**Comment by elmot** [comment]
That is not the way how plugins are installed 
Please read https://www.jetbrains.com/help/idea/managing-plugins.html
