### ISSUE TITLE
missing output when running code

### ISSUE THREAD

**Issue by Revilum** [JetBrains/intellij-micropython#208]
when I flash a simple hello world named main.py on the raspberry pi pico I don't get any stdout.
![grafik](https://user-images.githubusercontent.com/20228919/198838609-56f9713d-cfdf-4d68-bedc-375ccd8ad0b9.png)
interestingly when connecting with REPL and reset the device with CTRL+D hello world appears!
![grafik](https://user-images.githubusercontent.com/20228919/198838657-de13d4aa-fcb5-4e8e-a628-76105640e2e5.png)

looks like the ouput cuts off after requesting a reset?!

**Comment by vekunz** [comment]
This is normal. To see the output, you have to open a REPL yourself. The Flash window just shows the flashing progress and never the output.

**Comment by Revilum** [comment]
ok thanks. This seems like a bit of an unnecessary hustle for debugging code.

**Comment by vekunz** [comment]
Yes, currently the MicroPython support is very basic. But this may get optimized after the PR https://github.com/JetBrains/intellij-micropython/pull/139 is ready.
