### ISSUE TITLE
REPL complaining about 'Valid Interpreter'

### ISSUE THREAD

**Issue by DietrichChristopeit** [JetBrains/intellij-micropython#244]
The result is similar to #243 . The REPL can not be used in PyCharm 2023.2.
This is really a bit of a shame especially as the developers seem to ignore the issue.

Surely downgrading the whole PyCharm Installation works but that is even more of a shame.
I would be very grateful if this issue got solved swiftly.

**Comment by elmot** [comment]
Duplicate  #243, #285
