### ISSUE TITLE
micro python REPL

### ISSUE THREAD

**Issue by lenheard** [JetBrains/intellij-micropython#268]
micropython REPL does not startup
This is the pycharm I use...

PyCharm 2023.2.5 (Professional Edition)
Build #PY-232.10227.11, built on November 14, 2023
Licensed to Len Heard
You have a perpetual fallback license for this version.
Subscription is active until November 23, 2024.
Runtime version: 17.0.9+7-b1000.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10000M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    js.debugger.webconsole=false

Non-Bundled Plugins:
    com.andrey4623.rainbowcsv (2.0.2)
    ua.in.dej.myEmmet (1.2.5)
    com.intellij.ideolog (222.2.0.0)
    ChatGPT (3.1.7-231.232)
    com.github.redfoos.logstash-intellij-plugin (0.8.3)
    net.seesharpsoft.intellij.plugins.csv (3.2.3-232)
    intellij-micropython (1.4.2-2023.2)
    mobi.hsz.idea.gitignore (4.5.2)
    org.yseasony.sqlgenerator (2.2.1)

**Comment by nicholasmccall** [comment]
I'm having the same issue.  I can upload files to my pico w just fine but the REPL flashes with an empty line:
![image](https://github.com/JetBrains/intellij-micropython/assets/14790545/d9e5aa5a-8a79-430c-a682-9ed2f95db0e9)

**Comment by zerovijay** [comment]
MicroPython REPL not working again please fix this.

![Screenshot from 2023-12-07 10-34-26](https://github.com/JetBrains/intellij-micropython/assets/137445021/ade0441e-c972-411f-bfed-6f18e28727d3)

PyCharm 2023.3 (Community Edition)
Build #PC-233.11799.259, built on December 4, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.6.3-200.fc39.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 2
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  intellij-micropython (1.4.0)
Current Desktop: GNOME
