### ISSUE TITLE
MicroPython REPL not working again

### ISSUE THREAD

**Issue by zerovijay** [JetBrains/intellij-micropython#269]
# MicroPython REPL not working!

![Screenshot from 2023-12-07 10-34-26](https://github.com/JetBrains/intellij-micropython/assets/137445021/92b94822-d4a9-4733-a927-fc80f389bb81)

PyCharm 2023.3 (Community Edition)
Build #PC-233.11799.259, built on December 4, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.6.3-200.fc39.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 2
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  intellij-micropython (1.4.0)
Current Desktop: GNOME

**Comment by emcek** [comment]
Newest version of PyChram 2023.3 pick up older version of plugin `1.4.0`, see #270. So, despite of `1.4.2` not working ether with 2023.2
