### ISSUE TITLE
No 1.4.2 for 2023.3+

### ISSUE THREAD

**Issue by emcek** [JetBrains/intellij-micropython#270]
`1.4.2` is not listed for 2023.3 branch
![image](https://github.com/JetBrains/intellij-micropython/assets/475312/14a207bc-3ea3-40c9-9d3c-e0ddaaa968c8)

**Comment by zerovijay** [comment]
i can't understand!

**Comment by emcek** [comment]
`1.4.2` is compatible only with **2023.1.*** and **2023.2.*** (see table strict ranges)
but for **2023.3.*** is only available `1.4.0` since **2021.3+** regular expression

**Comment by zerovijay** [comment]
It's automatically upgraded i can't go below!

**Comment by zerovijay** [comment]
If I do something the no longer work micropython depending failed to download
Including manual installation

**Comment by gabemorris12** [comment]
@emcek The REPL console still doesn't work on Pycharm 2023.3.1 with Micropython 1.4.0. @zerovijay You can install previous versions of the Micropython plugin through [this page](https://plugins.jetbrains.com/plugin/9777-micropython/versions/stable). Follow the instructions after downloading.

**Comment by emcek** [comment]
As compatibly chart show... only `1.4.0` is compatibility with `2023.3.*` branch....
![image](https://github.com/JetBrains/intellij-micropython/assets/475312/dc75b4ad-fdaa-451b-a9c1-a0a652546105)
![image](https://github.com/JetBrains/intellij-micropython/assets/475312/fd519d0c-ad0a-4066-a31e-15a427b11148)
![image](https://github.com/JetBrains/intellij-micropython/assets/475312/cfd8fa60-10b9-42e2-8e9b-479d8a4a63dc)
