### ISSUE TITLE
MicroPython REPL stil not fixed!

### ISSUE THREAD

**Issue by zerovijay** [JetBrains/intellij-micropython#271]
# MicroPython REPL Not Working!

![Screenshot from 2023-12-14 04-25-48](https://github.com/JetBrains/intellij-micropython/assets/137445021/b61bc915-4dbe-4e51-bf30-f902fc8632b2)

PyCharm 2023.3.1 (Community Edition)
Build #PC-233.11799.298, built on December 12, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.6.4-200.fc39.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 2
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  intellij-micropython (1.4.0)
Current Desktop: GNOME

**Comment by osarhan** [comment]
Same here:

PyCharm 2023.3.1 (Professional Edition)
Build #PY-233.11799.298, built on December 11, 2023
Runtime version: 17.0.9+7-b1087.7 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  intellij-micropython (1.4.0)

**Comment by lenineto** [comment]
It's being 7 months now, 100s of complaints about the same issue, and it's still not fixed.
