### ISSUE TITLE
MicroPython REPL doesn't work with newest Pycharm

### ISSUE THREAD

**Issue by MATTYGILO** [JetBrains/intellij-micropython#275]
Version 2023.3
https://www.jetbrains.com/pycharm/download/other.html

**Comment by ianc1215** [comment]
Can confirm it also doesn't work with the patch version 2023.3.2.

**Comment by asdaraujo** [comment]
@ianc1215 please see [this](https://github.com/JetBrains/intellij-micropython/issues/274#issuecomment-1877979780) for a workaround until there's a fix

**Comment by ianc1215** [comment]
How about for Windows 11? This solution appears to be for Linux.

**Comment by britesc** [comment]
Bump
Can confirm VSCode and Thonny work perfectly as does mpremote.
Still not working in PyCharm.

**Comment by albertogomcas** [comment]
@ianc1215 Instead of dev/tty/... simply use the windows com port of your device

`python .\.repl\microrepl.py com11`

**Comment by walker2398** [comment]
It's now 2024.1,and my REPL still doesn't work.
