### ISSUE TITLE
Cannot use latest micropython plugin

### ISSUE THREAD

**Issue by SocIt2Em** [JetBrains/intellij-micropython#276]
In Pycharm and InteliJ only plugin version available is 1.4.0
Downloaded 1.4.2 and tried to install via install Plugin from Disk
Get ERROR 
<img width="325" alt="Screenshot_1" src="https://github.com/JetBrains/intellij-micropython/assets/22591056/16cd81e0-cba6-40bc-a94f-b54011369f60">

Get same type of error in PyCharm and IntelliJ

**Comment by SocIt2Em** [comment]
might be related to REPL and #270

**Comment by dseferlis** [comment]
Is there any progress to get REPL working on 2023.3? Is there any way to install 1.4.2 on 2023.3?

**Comment by rafaelmbs** [comment]
Waiting for it

**Comment by lancelote** [comment]
1.4.3 was released. It supports 2023.3+ versions.
