### ISSUE TITLE
Pycharm 241 Support + Repl fix

### ISSUE THREAD

**Issue by benno1237** [JetBrains/intellij-micropython#289]
The only version compatible with Pycharm 2024 is 1.40 which has broken REPL.

Turns out, version 1.43 of the plugin compiles just fine for build 241 and higher.
So anyone facing the same issue as I did, you can just clone the files, change the build number and you are good to go (I have no issue if that breaks anything else but upload and REPL is working fine so far for me).

Or, if you trust random dudes from the internet (which I wouldn't), here is a precompiled version of intellij-micropython v 1.43 for Pycharm 2024:
[intellij-micropython-SNAPSHOT.zip](https://github.com/JetBrains/intellij-micropython/files/15400326/intellij-micropython-SNAPSHOT.zip)
Follow this link for install instructions of local plugins: https://www.jetbrains.com/help/pycharm/managing-plugins.html

**Comment by ashirvadz** [comment]
Hi Benno.

I've installed your compiled version but the REPL is still broken (Shows "=== SESSION HAS BEEN INTERRUPTED ==="). I'm on Pycharm 2024.1.2.
I know this is not a lot of information, but do you think you could help me to get it going?
Thanks!

**Comment by benno1237** [comment]
I get the same thing sometimes but hitting 'restart' a few times always fixes it. See if it does the same for you. Otherwise I would highly recommend compiling it yourself.

**Comment by ashirvadz** [comment]
Thank you for the comment. 
I found the problem, which was a space after the device's address on the settings pane. 
The plugin is working now!

**Comment by benno1237** [comment]
Glad to hear that!

**Comment by GrumpyMetalGuy** [comment]
Seconded, I've also done this before reading this post, and it's worked for me too. If you get the keyboard interrupt, you can just run the code you want directly from the repl, not ideal, but does work.

**Comment by lancelote** [comment]
Should be fixed now with PyCharm 2024.1.4 + plugin 1.4.4.

**Comment by ashirvadz** [comment]
Great! Thank you @lancelote!
