### ISSUE TITLE
adafruit-ampy version

### ISSUE THREAD

**Issue by Omid888** [JetBrains/intellij-micropython#318]
Attempting to update the PyPI packages, breaks the plugin, Since the plugin only works with adafruit-ampy <1.1 version, but the latest version is 1.1.0
So I forced to rollback. Is this behavior intended? Can you inform us about the differences in adafruit-ampy versions?

**Comment by elmot** [comment]
Probably not. 
I'm planning to get rid of adafruit-ampy completely. See #297
